#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="UtmachBibliografia")]
	public partial class BDutmachBibliografiaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertRevistaCientifica(RevistaCientifica instance);
    partial void UpdateRevistaCientifica(RevistaCientifica instance);
    partial void DeleteRevistaCientifica(RevistaCientifica instance);
    partial void InsertActaCongreso(ActaCongreso instance);
    partial void UpdateActaCongreso(ActaCongreso instance);
    partial void DeleteActaCongreso(ActaCongreso instance);
    partial void InsertArticulo(Articulo instance);
    partial void UpdateArticulo(Articulo instance);
    partial void DeleteArticulo(Articulo instance);
    partial void InsertInformeTecnico(InformeTecnico instance);
    partial void UpdateInformeTecnico(InformeTecnico instance);
    partial void DeleteInformeTecnico(InformeTecnico instance);
    partial void InsertInvestigador(Investigador instance);
    partial void UpdateInvestigador(Investigador instance);
    partial void DeleteInvestigador(Investigador instance);
    #endregion
		
		public BDutmachBibliografiaDataContext() : 
				base(global::CapaDatos.Properties.Settings.Default.UtmachBibliografiaConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public BDutmachBibliografiaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDutmachBibliografiaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDutmachBibliografiaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDutmachBibliografiaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ActaArticulo> ActaArticulo
		{
			get
			{
				return this.GetTable<ActaArticulo>();
			}
		}
		
		public System.Data.Linq.Table<RevistaCientifica> RevistaCientifica
		{
			get
			{
				return this.GetTable<RevistaCientifica>();
			}
		}
		
		public System.Data.Linq.Table<ActaCongreso> ActaCongreso
		{
			get
			{
				return this.GetTable<ActaCongreso>();
			}
		}
		
		public System.Data.Linq.Table<Articulo> Articulo
		{
			get
			{
				return this.GetTable<Articulo>();
			}
		}
		
		public System.Data.Linq.Table<InformeArticulo> InformeArticulo
		{
			get
			{
				return this.GetTable<InformeArticulo>();
			}
		}
		
		public System.Data.Linq.Table<InformeTecnico> InformeTecnico
		{
			get
			{
				return this.GetTable<InformeTecnico>();
			}
		}
		
		public System.Data.Linq.Table<Investigador> Investigador
		{
			get
			{
				return this.GetTable<Investigador>();
			}
		}
		
		public System.Data.Linq.Table<InvestigadorArticulo> InvestigadorArticulo
		{
			get
			{
				return this.GetTable<InvestigadorArticulo>();
			}
		}
		
		public System.Data.Linq.Table<RevistaArticulo> RevistaArticulo
		{
			get
			{
				return this.GetTable<RevistaArticulo>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ActualizarArticulo")]
		public int CP_ActualizarArticulo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Titulo", DbType="VarChar(50)")] string titulo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PalabrasClaves", DbType="VarChar(50)")] string palabrasClaves, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contactos", DbType="VarChar(100)")] string contactos)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, titulo, palabrasClaves, contactos);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_EliminarArticulo")]
		public int CP_EliminarArticulo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_InsertarArticulo")]
		public int CP_InsertarArticulo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Titulo", DbType="VarChar(150)")] string titulo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PalabrasClave", DbType="VarChar(300)")] string palabrasClave, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contactos", DbType="VarChar(100)")] string contactos)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, titulo, palabrasClave, contactos);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ListarArticulo")]
		public ISingleResult<CP_ListarArticuloResult> CP_ListarArticulo()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<CP_ListarArticuloResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_listararticulosFiltro")]
		public ISingleResult<CP_listararticulosFiltroResult> CP_listararticulosFiltro([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<CP_listararticulosFiltroResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ActualizarActaCongreso")]
		public int CP_ActualizarActaCongreso([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(200)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Edicion", DbType="VarChar(50)")] string edicion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CiudadCelebracion", DbType="VarChar(150)")] string ciudadCelebracion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaInicio", DbType="Date")] System.Nullable<System.DateTime> fechaInicio, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaFinalizacion", DbType="Date")] System.Nullable<System.DateTime> fechaFinalizacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoCongreso", DbType="VarChar(50)")] string tipoCongreso, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pais", DbType="VarChar(150)")] string pais, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AñoPrimeraCelebracion", DbType="VarChar(100)")] string añoPrimeraCelebracion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Frecuencia", DbType="VarChar(50)")] string frecuencia)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, nombre, edicion, ciudadCelebracion, fechaInicio, fechaFinalizacion, tipoCongreso, pais, añoPrimeraCelebracion, frecuencia);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ActualizarInformeTecnico")]
		public int CP_ActualizarInformeTecnico([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Numero", DbType="VarChar(100)")] string numero, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CentroPublicacion", DbType="VarChar(100)")] string centroPublicacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MesPublicacion", DbType="VarChar(60)")] string mesPublicacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AñoPublicacion", DbType="VarChar(100)")] string añoPublicacion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, numero, centroPublicacion, mesPublicacion, añoPublicacion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ActualizarInvestigador")]
		public int CP_ActualizarInvestigador([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(25)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string centro, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string temas)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, nombre, centro, correo, temas);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ActualizarRevistaCientifica")]
		public int CP_ActualizarRevistaCientifica([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Editor", DbType="VarChar(50)")] string editor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AnioInicioPublicacion", DbType="DateTime")] System.Nullable<System.DateTime> anioInicioPublicacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Frecuencia", DbType="VarChar(50)")] string frecuencia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Temas", DbType="VarChar(200)")] string temas, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Numero", DbType="Int")] System.Nullable<int> numero, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AnioPublicacion", DbType="DateTime")] System.Nullable<System.DateTime> anioPublicacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Costo", DbType="Decimal(18,0)")] System.Nullable<decimal> costo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, nombre, editor, anioInicioPublicacion, frecuencia, temas, numero, anioPublicacion, costo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_EliminarActaCongreso")]
		public int CP_EliminarActaCongreso([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_EliminarInformeTecnico")]
		public int CP_EliminarInformeTecnico([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Cp_EliminarInvestigador")]
		public int Cp_EliminarInvestigador([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_EliminarRevistaCientifica")]
		public int CP_EliminarRevistaCientifica([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_InsertarActaCongreso")]
		public int CP_InsertarActaCongreso([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(200)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Edicion", DbType="VarChar(50)")] string edicion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CiudadCelebracion", DbType="VarChar(150)")] string ciudadCelebracion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaInicio", DbType="Date")] System.Nullable<System.DateTime> fechaInicio, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaFinalizacion", DbType="Date")] System.Nullable<System.DateTime> fechaFinalizacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoCongreso", DbType="VarChar(50)")] string tipoCongreso, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pais", DbType="VarChar(150)")] string pais, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AñoPrimeraCelebracion", DbType="VarChar(100)")] string añoPrimeraCelebracion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Frecuencia", DbType="VarChar(50)")] string frecuencia)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, nombre, edicion, ciudadCelebracion, fechaInicio, fechaFinalizacion, tipoCongreso, pais, añoPrimeraCelebracion, frecuencia);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_InsertarInformeTecnico")]
		public int CP_InsertarInformeTecnico([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Numero", DbType="VarChar(100)")] string numero, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CentroPublicacion", DbType="VarChar(100)")] string centroPublicacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MesPublicacion", DbType="VarChar(60)")] string mesPublicacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AñoPublicacion", DbType="VarChar(100)")] string añoPublicacion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, numero, centroPublicacion, mesPublicacion, añoPublicacion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_InsertarInvestigador")]
		public int CP_InsertarInvestigador([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(25)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string centro, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string temas)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, nombre, centro, correo, temas);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_listaractaCongresoFiltro")]
		public ISingleResult<CP_listaractaCongresoFiltroResult> CP_listaractaCongresoFiltro([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<CP_listaractaCongresoFiltroResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_listarinformeTecnicoFiltro")]
		public ISingleResult<CP_listarinformeTecnicoFiltroResult> CP_listarinformeTecnicoFiltro([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<CP_listarinformeTecnicoFiltroResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ListarInvestigador")]
		public ISingleResult<CP_ListarInvestigadorResult> CP_ListarInvestigador()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<CP_ListarInvestigadorResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ListarInvestigadorFiltro")]
		public ISingleResult<CP_ListarInvestigadorFiltroResult> CP_ListarInvestigadorFiltro([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<CP_ListarInvestigadorFiltroResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_listarRevistaCientificaFiltro")]
		public ISingleResult<CP_listarRevistaCientificaFiltroResult> CP_listarRevistaCientificaFiltro([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<CP_listarRevistaCientificaFiltroResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ListarInformeTecnico")]
		public ISingleResult<CP_ListarInformeTecnicoResult> CP_ListarInformeTecnico()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<CP_ListarInformeTecnicoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ListarRevistaCientifica")]
		public ISingleResult<CP_ListarRevistaCientificaResult> CP_ListarRevistaCientifica()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<CP_ListarRevistaCientificaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_InsertarRevistaCientifica")]
		public int CP_InsertarRevistaCientifica([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string editor, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> anioinicio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string frecuencia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string temas, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> numero, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> aniopublicacionactual, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> costo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, nombre, editor, anioinicio, frecuencia, temas, numero, aniopublicacionactual, costo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ListarActaCongreso")]
		public ISingleResult<CP_ListarActaCongresoResult> CP_ListarActaCongreso()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<CP_ListarActaCongresoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_InsertarInvestigador_Articulo")]
		public int CP_InsertarInvestigador_Articulo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_investigador", DbType="Int")] System.Nullable<int> iD_investigador, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_articulo", DbType="Int")] System.Nullable<int> iD_articulo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_investigador, iD_articulo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ListarInvestigador_Articulo")]
		public ISingleResult<CP_ListarInvestigador_ArticuloResult> CP_ListarInvestigador_Articulo()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<CP_ListarInvestigador_ArticuloResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ListarInvestigador_ArticuloFiltro")]
		public ISingleResult<CP_ListarInvestigador_ArticuloFiltroResult> CP_ListarInvestigador_ArticuloFiltro([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2)")] string value)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), value);
			return ((ISingleResult<CP_ListarInvestigador_ArticuloFiltroResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ListarInvestigadores_Articulos")]
		public ISingleResult<CP_ListarInvestigadores_ArticulosResult> CP_ListarInvestigadores_Articulos()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<CP_ListarInvestigadores_ArticulosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_EliminarInvestigadorArticulo")]
		public int CP_EliminarInvestigadorArticulo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_articulo", DbType="Int")] System.Nullable<int> iD_articulo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_investigador", DbType="Int")] System.Nullable<int> iD_investigador)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_articulo, iD_investigador);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_EliminarActaArticulo")]
		public int CP_EliminarActaArticulo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idacta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idarticulo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idacta, idarticulo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_EliminarInformeArticulo")]
		public int CP_EliminarInformeArticulo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idinforme, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idarticulo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idinforme, idarticulo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_EliminarRevistaArticulo")]
		public int CP_EliminarRevistaArticulo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idacta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idarticulo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idacta, idarticulo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_InsertarActaArticulo")]
		public int CP_InsertarActaArticulo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idacta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idarticulo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idacta, idarticulo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_InsertarInformeArticulo")]
		public int CP_InsertarInformeArticulo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idinforme, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idarticulo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idinforme, idarticulo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_InsertRevistaArticulo")]
		public int CP_InsertRevistaArticulo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idrevista, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idarticulo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idrevista, idarticulo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ListarActaArticulo")]
		public ISingleResult<CP_ListarActaArticuloResult> CP_ListarActaArticulo()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<CP_ListarActaArticuloResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ListarActaArticuloFiltro")]
		public ISingleResult<CP_ListarActaArticuloFiltroResult> CP_ListarActaArticuloFiltro([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4)")] string value)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), value);
			return ((ISingleResult<CP_ListarActaArticuloFiltroResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ListarInformeArticulo")]
		public ISingleResult<CP_ListarInformeArticuloResult> CP_ListarInformeArticulo()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<CP_ListarInformeArticuloResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ListarInformeArticuloFiltro")]
		public ISingleResult<CP_ListarInformeArticuloFiltroResult> CP_ListarInformeArticuloFiltro([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4)")] string value)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), value);
			return ((ISingleResult<CP_ListarInformeArticuloFiltroResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ListarV2RevistaArticulo")]
		public ISingleResult<CP_ListarV2RevistaArticuloResult> CP_ListarV2RevistaArticulo()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<CP_ListarV2RevistaArticuloResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ListarV2InformeArticulo")]
		public ISingleResult<CP_ListarV2InformeArticuloResult> CP_ListarV2InformeArticulo()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<CP_ListarV2InformeArticuloResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ListarV2ActaArticulo")]
		public ISingleResult<CP_ListarV2ActaArticuloResult> CP_ListarV2ActaArticulo()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<CP_ListarV2ActaArticuloResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ListarRevistaArticulo")]
		public ISingleResult<CP_ListarRevistaArticuloResult> CP_ListarRevistaArticulo()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<CP_ListarRevistaArticuloResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ActualizarInvestigadorArticulo")]
		public int CP_ActualizarInvestigadorArticulo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_investigador", DbType="Int")] System.Nullable<int> iD_investigador, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_articulo", DbType="Int")] System.Nullable<int> iD_articulo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> aux_inv)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_investigador, iD_articulo, aux_inv);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ActualizarActaArticulo")]
		public int CP_ActualizarActaArticulo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idacta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idarticulo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> auxacta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idacta, idarticulo, auxacta);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ActualizarInformeArticulo")]
		public int CP_ActualizarInformeArticulo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idinforme, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idarticulo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> auxinf)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idinforme, idarticulo, auxinf);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ActualizarRevistaArticulo")]
		public int CP_ActualizarRevistaArticulo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idrevista, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idarticulo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> auxrev)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idrevista, idarticulo, auxrev);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ActaArticulo")]
	public partial class ActaArticulo
	{
		
		private int _id_actacongreso;
		
		private int _id_articulo;
		
		public ActaArticulo()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_actacongreso", DbType="Int NOT NULL")]
		public int id_actacongreso
		{
			get
			{
				return this._id_actacongreso;
			}
			set
			{
				if ((this._id_actacongreso != value))
				{
					this._id_actacongreso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_articulo", DbType="Int NOT NULL")]
		public int id_articulo
		{
			get
			{
				return this._id_articulo;
			}
			set
			{
				if ((this._id_articulo != value))
				{
					this._id_articulo = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RevistaCientifica")]
	public partial class RevistaCientifica : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_revista;
		
		private string _Nombre;
		
		private string _Editor;
		
		private System.Nullable<System.DateTime> _AnioInicioPublicacion;
		
		private string _Frecuencia;
		
		private string _Temas;
		
		private System.Nullable<int> _Numero;
		
		private System.Nullable<System.DateTime> _AnioPublicacionActual;
		
		private System.Nullable<decimal> _Costo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_revistaChanging(int value);
    partial void Onid_revistaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnEditorChanging(string value);
    partial void OnEditorChanged();
    partial void OnAnioInicioPublicacionChanging(System.Nullable<System.DateTime> value);
    partial void OnAnioInicioPublicacionChanged();
    partial void OnFrecuenciaChanging(string value);
    partial void OnFrecuenciaChanged();
    partial void OnTemasChanging(string value);
    partial void OnTemasChanged();
    partial void OnNumeroChanging(System.Nullable<int> value);
    partial void OnNumeroChanged();
    partial void OnAnioPublicacionActualChanging(System.Nullable<System.DateTime> value);
    partial void OnAnioPublicacionActualChanged();
    partial void OnCostoChanging(System.Nullable<decimal> value);
    partial void OnCostoChanged();
    #endregion
		
		public RevistaCientifica()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_revista", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_revista
		{
			get
			{
				return this._id_revista;
			}
			set
			{
				if ((this._id_revista != value))
				{
					this.Onid_revistaChanging(value);
					this.SendPropertyChanging();
					this._id_revista = value;
					this.SendPropertyChanged("id_revista");
					this.Onid_revistaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Editor", DbType="VarChar(50)")]
		public string Editor
		{
			get
			{
				return this._Editor;
			}
			set
			{
				if ((this._Editor != value))
				{
					this.OnEditorChanging(value);
					this.SendPropertyChanging();
					this._Editor = value;
					this.SendPropertyChanged("Editor");
					this.OnEditorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnioInicioPublicacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> AnioInicioPublicacion
		{
			get
			{
				return this._AnioInicioPublicacion;
			}
			set
			{
				if ((this._AnioInicioPublicacion != value))
				{
					this.OnAnioInicioPublicacionChanging(value);
					this.SendPropertyChanging();
					this._AnioInicioPublicacion = value;
					this.SendPropertyChanged("AnioInicioPublicacion");
					this.OnAnioInicioPublicacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Frecuencia", DbType="VarChar(50)")]
		public string Frecuencia
		{
			get
			{
				return this._Frecuencia;
			}
			set
			{
				if ((this._Frecuencia != value))
				{
					this.OnFrecuenciaChanging(value);
					this.SendPropertyChanging();
					this._Frecuencia = value;
					this.SendPropertyChanged("Frecuencia");
					this.OnFrecuenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Temas", DbType="VarChar(50)")]
		public string Temas
		{
			get
			{
				return this._Temas;
			}
			set
			{
				if ((this._Temas != value))
				{
					this.OnTemasChanging(value);
					this.SendPropertyChanging();
					this._Temas = value;
					this.SendPropertyChanged("Temas");
					this.OnTemasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numero", DbType="Int")]
		public System.Nullable<int> Numero
		{
			get
			{
				return this._Numero;
			}
			set
			{
				if ((this._Numero != value))
				{
					this.OnNumeroChanging(value);
					this.SendPropertyChanging();
					this._Numero = value;
					this.SendPropertyChanged("Numero");
					this.OnNumeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnioPublicacionActual", DbType="DateTime")]
		public System.Nullable<System.DateTime> AnioPublicacionActual
		{
			get
			{
				return this._AnioPublicacionActual;
			}
			set
			{
				if ((this._AnioPublicacionActual != value))
				{
					this.OnAnioPublicacionActualChanging(value);
					this.SendPropertyChanging();
					this._AnioPublicacionActual = value;
					this.SendPropertyChanged("AnioPublicacionActual");
					this.OnAnioPublicacionActualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Costo", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Costo
		{
			get
			{
				return this._Costo;
			}
			set
			{
				if ((this._Costo != value))
				{
					this.OnCostoChanging(value);
					this.SendPropertyChanging();
					this._Costo = value;
					this.SendPropertyChanged("Costo");
					this.OnCostoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ActaCongreso")]
	public partial class ActaCongreso : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_actacongreso;
		
		private string _NombreCongreso;
		
		private string _Edicion;
		
		private string _CiudadCelebracion;
		
		private System.Nullable<System.DateTime> _FechaInicio;
		
		private System.Nullable<System.DateTime> _FechaFinalizacion;
		
		private string _TipoCongreso;
		
		private string _Pais;
		
		private string _AñoPrimeraCelebracion;
		
		private string _Frecuencia;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_actacongresoChanging(int value);
    partial void Onid_actacongresoChanged();
    partial void OnNombreCongresoChanging(string value);
    partial void OnNombreCongresoChanged();
    partial void OnEdicionChanging(string value);
    partial void OnEdicionChanged();
    partial void OnCiudadCelebracionChanging(string value);
    partial void OnCiudadCelebracionChanged();
    partial void OnFechaInicioChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaInicioChanged();
    partial void OnFechaFinalizacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaFinalizacionChanged();
    partial void OnTipoCongresoChanging(string value);
    partial void OnTipoCongresoChanged();
    partial void OnPaisChanging(string value);
    partial void OnPaisChanged();
    partial void OnAñoPrimeraCelebracionChanging(string value);
    partial void OnAñoPrimeraCelebracionChanged();
    partial void OnFrecuenciaChanging(string value);
    partial void OnFrecuenciaChanged();
    #endregion
		
		public ActaCongreso()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_actacongreso", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_actacongreso
		{
			get
			{
				return this._id_actacongreso;
			}
			set
			{
				if ((this._id_actacongreso != value))
				{
					this.Onid_actacongresoChanging(value);
					this.SendPropertyChanging();
					this._id_actacongreso = value;
					this.SendPropertyChanged("id_actacongreso");
					this.Onid_actacongresoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCongreso", DbType="VarChar(200)")]
		public string NombreCongreso
		{
			get
			{
				return this._NombreCongreso;
			}
			set
			{
				if ((this._NombreCongreso != value))
				{
					this.OnNombreCongresoChanging(value);
					this.SendPropertyChanging();
					this._NombreCongreso = value;
					this.SendPropertyChanged("NombreCongreso");
					this.OnNombreCongresoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Edicion", DbType="VarChar(50)")]
		public string Edicion
		{
			get
			{
				return this._Edicion;
			}
			set
			{
				if ((this._Edicion != value))
				{
					this.OnEdicionChanging(value);
					this.SendPropertyChanging();
					this._Edicion = value;
					this.SendPropertyChanged("Edicion");
					this.OnEdicionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CiudadCelebracion", DbType="VarChar(150)")]
		public string CiudadCelebracion
		{
			get
			{
				return this._CiudadCelebracion;
			}
			set
			{
				if ((this._CiudadCelebracion != value))
				{
					this.OnCiudadCelebracionChanging(value);
					this.SendPropertyChanging();
					this._CiudadCelebracion = value;
					this.SendPropertyChanged("CiudadCelebracion");
					this.OnCiudadCelebracionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaInicio", DbType="Date")]
		public System.Nullable<System.DateTime> FechaInicio
		{
			get
			{
				return this._FechaInicio;
			}
			set
			{
				if ((this._FechaInicio != value))
				{
					this.OnFechaInicioChanging(value);
					this.SendPropertyChanging();
					this._FechaInicio = value;
					this.SendPropertyChanged("FechaInicio");
					this.OnFechaInicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaFinalizacion", DbType="Date")]
		public System.Nullable<System.DateTime> FechaFinalizacion
		{
			get
			{
				return this._FechaFinalizacion;
			}
			set
			{
				if ((this._FechaFinalizacion != value))
				{
					this.OnFechaFinalizacionChanging(value);
					this.SendPropertyChanging();
					this._FechaFinalizacion = value;
					this.SendPropertyChanged("FechaFinalizacion");
					this.OnFechaFinalizacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoCongreso", DbType="VarChar(40)")]
		public string TipoCongreso
		{
			get
			{
				return this._TipoCongreso;
			}
			set
			{
				if ((this._TipoCongreso != value))
				{
					this.OnTipoCongresoChanging(value);
					this.SendPropertyChanging();
					this._TipoCongreso = value;
					this.SendPropertyChanged("TipoCongreso");
					this.OnTipoCongresoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pais", DbType="VarChar(150)")]
		public string Pais
		{
			get
			{
				return this._Pais;
			}
			set
			{
				if ((this._Pais != value))
				{
					this.OnPaisChanging(value);
					this.SendPropertyChanging();
					this._Pais = value;
					this.SendPropertyChanged("Pais");
					this.OnPaisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AñoPrimeraCelebracion", DbType="VarChar(100)")]
		public string AñoPrimeraCelebracion
		{
			get
			{
				return this._AñoPrimeraCelebracion;
			}
			set
			{
				if ((this._AñoPrimeraCelebracion != value))
				{
					this.OnAñoPrimeraCelebracionChanging(value);
					this.SendPropertyChanging();
					this._AñoPrimeraCelebracion = value;
					this.SendPropertyChanged("AñoPrimeraCelebracion");
					this.OnAñoPrimeraCelebracionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Frecuencia", DbType="VarChar(50)")]
		public string Frecuencia
		{
			get
			{
				return this._Frecuencia;
			}
			set
			{
				if ((this._Frecuencia != value))
				{
					this.OnFrecuenciaChanging(value);
					this.SendPropertyChanging();
					this._Frecuencia = value;
					this.SendPropertyChanged("Frecuencia");
					this.OnFrecuenciaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Articulo")]
	public partial class Articulo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_articulo;
		
		private string _Titulo;
		
		private string _PalabrasClave;
		
		private string _Contactos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_articuloChanging(int value);
    partial void Onid_articuloChanged();
    partial void OnTituloChanging(string value);
    partial void OnTituloChanged();
    partial void OnPalabrasClaveChanging(string value);
    partial void OnPalabrasClaveChanged();
    partial void OnContactosChanging(string value);
    partial void OnContactosChanged();
    #endregion
		
		public Articulo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_articulo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_articulo
		{
			get
			{
				return this._id_articulo;
			}
			set
			{
				if ((this._id_articulo != value))
				{
					this.Onid_articuloChanging(value);
					this.SendPropertyChanging();
					this._id_articulo = value;
					this.SendPropertyChanged("id_articulo");
					this.Onid_articuloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulo", DbType="VarChar(150)")]
		public string Titulo
		{
			get
			{
				return this._Titulo;
			}
			set
			{
				if ((this._Titulo != value))
				{
					this.OnTituloChanging(value);
					this.SendPropertyChanging();
					this._Titulo = value;
					this.SendPropertyChanged("Titulo");
					this.OnTituloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PalabrasClave", DbType="VarChar(300)")]
		public string PalabrasClave
		{
			get
			{
				return this._PalabrasClave;
			}
			set
			{
				if ((this._PalabrasClave != value))
				{
					this.OnPalabrasClaveChanging(value);
					this.SendPropertyChanging();
					this._PalabrasClave = value;
					this.SendPropertyChanged("PalabrasClave");
					this.OnPalabrasClaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contactos", DbType="VarChar(100)")]
		public string Contactos
		{
			get
			{
				return this._Contactos;
			}
			set
			{
				if ((this._Contactos != value))
				{
					this.OnContactosChanging(value);
					this.SendPropertyChanging();
					this._Contactos = value;
					this.SendPropertyChanged("Contactos");
					this.OnContactosChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.InformeArticulo")]
	public partial class InformeArticulo
	{
		
		private int _id_informe;
		
		private int _id_articulo;
		
		public InformeArticulo()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_informe", DbType="Int NOT NULL")]
		public int id_informe
		{
			get
			{
				return this._id_informe;
			}
			set
			{
				if ((this._id_informe != value))
				{
					this._id_informe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_articulo", DbType="Int NOT NULL")]
		public int id_articulo
		{
			get
			{
				return this._id_articulo;
			}
			set
			{
				if ((this._id_articulo != value))
				{
					this._id_articulo = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.InformeTecnico")]
	public partial class InformeTecnico : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_informe;
		
		private string _Numero;
		
		private string _CentroPublicacion;
		
		private string _MesPublicacion;
		
		private string _AñoPublicacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_informeChanging(int value);
    partial void Onid_informeChanged();
    partial void OnNumeroChanging(string value);
    partial void OnNumeroChanged();
    partial void OnCentroPublicacionChanging(string value);
    partial void OnCentroPublicacionChanged();
    partial void OnMesPublicacionChanging(string value);
    partial void OnMesPublicacionChanged();
    partial void OnAñoPublicacionChanging(string value);
    partial void OnAñoPublicacionChanged();
    #endregion
		
		public InformeTecnico()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_informe", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_informe
		{
			get
			{
				return this._id_informe;
			}
			set
			{
				if ((this._id_informe != value))
				{
					this.Onid_informeChanging(value);
					this.SendPropertyChanging();
					this._id_informe = value;
					this.SendPropertyChanged("id_informe");
					this.Onid_informeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numero", DbType="VarChar(100)")]
		public string Numero
		{
			get
			{
				return this._Numero;
			}
			set
			{
				if ((this._Numero != value))
				{
					this.OnNumeroChanging(value);
					this.SendPropertyChanging();
					this._Numero = value;
					this.SendPropertyChanged("Numero");
					this.OnNumeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CentroPublicacion", DbType="VarChar(100)")]
		public string CentroPublicacion
		{
			get
			{
				return this._CentroPublicacion;
			}
			set
			{
				if ((this._CentroPublicacion != value))
				{
					this.OnCentroPublicacionChanging(value);
					this.SendPropertyChanging();
					this._CentroPublicacion = value;
					this.SendPropertyChanged("CentroPublicacion");
					this.OnCentroPublicacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MesPublicacion", DbType="VarChar(60)")]
		public string MesPublicacion
		{
			get
			{
				return this._MesPublicacion;
			}
			set
			{
				if ((this._MesPublicacion != value))
				{
					this.OnMesPublicacionChanging(value);
					this.SendPropertyChanging();
					this._MesPublicacion = value;
					this.SendPropertyChanged("MesPublicacion");
					this.OnMesPublicacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AñoPublicacion", DbType="VarChar(100)")]
		public string AñoPublicacion
		{
			get
			{
				return this._AñoPublicacion;
			}
			set
			{
				if ((this._AñoPublicacion != value))
				{
					this.OnAñoPublicacionChanging(value);
					this.SendPropertyChanging();
					this._AñoPublicacion = value;
					this.SendPropertyChanged("AñoPublicacion");
					this.OnAñoPublicacionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Investigador")]
	public partial class Investigador : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_investigador;
		
		private string _Nombre;
		
		private string _CentroTrabajo;
		
		private string _Correo;
		
		private string _Temas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_investigadorChanging(int value);
    partial void Onid_investigadorChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnCentroTrabajoChanging(string value);
    partial void OnCentroTrabajoChanged();
    partial void OnCorreoChanging(string value);
    partial void OnCorreoChanged();
    partial void OnTemasChanging(string value);
    partial void OnTemasChanged();
    #endregion
		
		public Investigador()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_investigador", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_investigador
		{
			get
			{
				return this._id_investigador;
			}
			set
			{
				if ((this._id_investigador != value))
				{
					this.Onid_investigadorChanging(value);
					this.SendPropertyChanging();
					this._id_investigador = value;
					this.SendPropertyChanged("id_investigador");
					this.Onid_investigadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CentroTrabajo", DbType="VarChar(100)")]
		public string CentroTrabajo
		{
			get
			{
				return this._CentroTrabajo;
			}
			set
			{
				if ((this._CentroTrabajo != value))
				{
					this.OnCentroTrabajoChanging(value);
					this.SendPropertyChanging();
					this._CentroTrabajo = value;
					this.SendPropertyChanged("CentroTrabajo");
					this.OnCentroTrabajoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(100)")]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this.OnCorreoChanging(value);
					this.SendPropertyChanging();
					this._Correo = value;
					this.SendPropertyChanged("Correo");
					this.OnCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Temas", DbType="VarChar(100)")]
		public string Temas
		{
			get
			{
				return this._Temas;
			}
			set
			{
				if ((this._Temas != value))
				{
					this.OnTemasChanging(value);
					this.SendPropertyChanging();
					this._Temas = value;
					this.SendPropertyChanged("Temas");
					this.OnTemasChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.InvestigadorArticulo")]
	public partial class InvestigadorArticulo
	{
		
		private int _id_investigador;
		
		private int _id_articulo;
		
		public InvestigadorArticulo()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_investigador", DbType="Int NOT NULL")]
		public int id_investigador
		{
			get
			{
				return this._id_investigador;
			}
			set
			{
				if ((this._id_investigador != value))
				{
					this._id_investigador = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_articulo", DbType="Int NOT NULL")]
		public int id_articulo
		{
			get
			{
				return this._id_articulo;
			}
			set
			{
				if ((this._id_articulo != value))
				{
					this._id_articulo = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RevistaArticulo")]
	public partial class RevistaArticulo
	{
		
		private System.Nullable<int> _IdRevista;
		
		private System.Nullable<int> _IdArticulo;
		
		public RevistaArticulo()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRevista", DbType="Int")]
		public System.Nullable<int> IdRevista
		{
			get
			{
				return this._IdRevista;
			}
			set
			{
				if ((this._IdRevista != value))
				{
					this._IdRevista = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdArticulo", DbType="Int")]
		public System.Nullable<int> IdArticulo
		{
			get
			{
				return this._IdArticulo;
			}
			set
			{
				if ((this._IdArticulo != value))
				{
					this._IdArticulo = value;
				}
			}
		}
	}
	
	public partial class CP_ListarArticuloResult
	{
		
		private int _id_articulo;
		
		private string _Titulo;
		
		private string _PalabrasClave;
		
		private string _Contactos;
		
		public CP_ListarArticuloResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_articulo", DbType="Int NOT NULL")]
		public int id_articulo
		{
			get
			{
				return this._id_articulo;
			}
			set
			{
				if ((this._id_articulo != value))
				{
					this._id_articulo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulo", DbType="VarChar(150)")]
		public string Titulo
		{
			get
			{
				return this._Titulo;
			}
			set
			{
				if ((this._Titulo != value))
				{
					this._Titulo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PalabrasClave", DbType="VarChar(300)")]
		public string PalabrasClave
		{
			get
			{
				return this._PalabrasClave;
			}
			set
			{
				if ((this._PalabrasClave != value))
				{
					this._PalabrasClave = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contactos", DbType="VarChar(100)")]
		public string Contactos
		{
			get
			{
				return this._Contactos;
			}
			set
			{
				if ((this._Contactos != value))
				{
					this._Contactos = value;
				}
			}
		}
	}
	
	public partial class CP_listararticulosFiltroResult
	{
		
		private int _id_articulo;
		
		private string _Titulo;
		
		private string _PalabrasClave;
		
		private string _Contactos;
		
		public CP_listararticulosFiltroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_articulo", DbType="Int NOT NULL")]
		public int id_articulo
		{
			get
			{
				return this._id_articulo;
			}
			set
			{
				if ((this._id_articulo != value))
				{
					this._id_articulo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulo", DbType="VarChar(150)")]
		public string Titulo
		{
			get
			{
				return this._Titulo;
			}
			set
			{
				if ((this._Titulo != value))
				{
					this._Titulo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PalabrasClave", DbType="VarChar(300)")]
		public string PalabrasClave
		{
			get
			{
				return this._PalabrasClave;
			}
			set
			{
				if ((this._PalabrasClave != value))
				{
					this._PalabrasClave = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contactos", DbType="VarChar(100)")]
		public string Contactos
		{
			get
			{
				return this._Contactos;
			}
			set
			{
				if ((this._Contactos != value))
				{
					this._Contactos = value;
				}
			}
		}
	}
	
	public partial class CP_listaractaCongresoFiltroResult
	{
		
		private int _id_actacongreso;
		
		private string _NombreCongreso;
		
		private string _Edicion;
		
		private string _CiudadCelebracion;
		
		private System.Nullable<System.DateTime> _FechaInicio;
		
		private System.Nullable<System.DateTime> _FechaFinalizacion;
		
		private string _TipoCongreso;
		
		private string _Pais;
		
		private string _AñoPrimeraCelebracion;
		
		private string _Frecuencia;
		
		public CP_listaractaCongresoFiltroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_actacongreso", DbType="Int NOT NULL")]
		public int id_actacongreso
		{
			get
			{
				return this._id_actacongreso;
			}
			set
			{
				if ((this._id_actacongreso != value))
				{
					this._id_actacongreso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCongreso", DbType="VarChar(200)")]
		public string NombreCongreso
		{
			get
			{
				return this._NombreCongreso;
			}
			set
			{
				if ((this._NombreCongreso != value))
				{
					this._NombreCongreso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Edicion", DbType="VarChar(50)")]
		public string Edicion
		{
			get
			{
				return this._Edicion;
			}
			set
			{
				if ((this._Edicion != value))
				{
					this._Edicion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CiudadCelebracion", DbType="VarChar(150)")]
		public string CiudadCelebracion
		{
			get
			{
				return this._CiudadCelebracion;
			}
			set
			{
				if ((this._CiudadCelebracion != value))
				{
					this._CiudadCelebracion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaInicio", DbType="Date")]
		public System.Nullable<System.DateTime> FechaInicio
		{
			get
			{
				return this._FechaInicio;
			}
			set
			{
				if ((this._FechaInicio != value))
				{
					this._FechaInicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaFinalizacion", DbType="Date")]
		public System.Nullable<System.DateTime> FechaFinalizacion
		{
			get
			{
				return this._FechaFinalizacion;
			}
			set
			{
				if ((this._FechaFinalizacion != value))
				{
					this._FechaFinalizacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoCongreso", DbType="VarChar(40)")]
		public string TipoCongreso
		{
			get
			{
				return this._TipoCongreso;
			}
			set
			{
				if ((this._TipoCongreso != value))
				{
					this._TipoCongreso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pais", DbType="VarChar(150)")]
		public string Pais
		{
			get
			{
				return this._Pais;
			}
			set
			{
				if ((this._Pais != value))
				{
					this._Pais = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AñoPrimeraCelebracion", DbType="VarChar(100)")]
		public string AñoPrimeraCelebracion
		{
			get
			{
				return this._AñoPrimeraCelebracion;
			}
			set
			{
				if ((this._AñoPrimeraCelebracion != value))
				{
					this._AñoPrimeraCelebracion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Frecuencia", DbType="VarChar(50)")]
		public string Frecuencia
		{
			get
			{
				return this._Frecuencia;
			}
			set
			{
				if ((this._Frecuencia != value))
				{
					this._Frecuencia = value;
				}
			}
		}
	}
	
	public partial class CP_listarinformeTecnicoFiltroResult
	{
		
		private int _id_informe;
		
		private string _Numero;
		
		private string _CentroPublicacion;
		
		private string _MesPublicacion;
		
		private string _AñoPublicacion;
		
		public CP_listarinformeTecnicoFiltroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_informe", DbType="Int NOT NULL")]
		public int id_informe
		{
			get
			{
				return this._id_informe;
			}
			set
			{
				if ((this._id_informe != value))
				{
					this._id_informe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numero", DbType="VarChar(100)")]
		public string Numero
		{
			get
			{
				return this._Numero;
			}
			set
			{
				if ((this._Numero != value))
				{
					this._Numero = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CentroPublicacion", DbType="VarChar(100)")]
		public string CentroPublicacion
		{
			get
			{
				return this._CentroPublicacion;
			}
			set
			{
				if ((this._CentroPublicacion != value))
				{
					this._CentroPublicacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MesPublicacion", DbType="VarChar(60)")]
		public string MesPublicacion
		{
			get
			{
				return this._MesPublicacion;
			}
			set
			{
				if ((this._MesPublicacion != value))
				{
					this._MesPublicacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AñoPublicacion", DbType="VarChar(100)")]
		public string AñoPublicacion
		{
			get
			{
				return this._AñoPublicacion;
			}
			set
			{
				if ((this._AñoPublicacion != value))
				{
					this._AñoPublicacion = value;
				}
			}
		}
	}
	
	public partial class CP_ListarInvestigadorResult
	{
		
		private int _id_investigador;
		
		private string _Nombre;
		
		private string _CentroTrabajo;
		
		private string _Correo;
		
		private string _Temas;
		
		public CP_ListarInvestigadorResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_investigador", DbType="Int NOT NULL")]
		public int id_investigador
		{
			get
			{
				return this._id_investigador;
			}
			set
			{
				if ((this._id_investigador != value))
				{
					this._id_investigador = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CentroTrabajo", DbType="VarChar(100)")]
		public string CentroTrabajo
		{
			get
			{
				return this._CentroTrabajo;
			}
			set
			{
				if ((this._CentroTrabajo != value))
				{
					this._CentroTrabajo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(100)")]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this._Correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Temas", DbType="VarChar(100)")]
		public string Temas
		{
			get
			{
				return this._Temas;
			}
			set
			{
				if ((this._Temas != value))
				{
					this._Temas = value;
				}
			}
		}
	}
	
	public partial class CP_ListarInvestigadorFiltroResult
	{
		
		private int _id_investigador;
		
		private string _Nombre;
		
		private string _CentroTrabajo;
		
		private string _Correo;
		
		private string _Temas;
		
		public CP_ListarInvestigadorFiltroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_investigador", DbType="Int NOT NULL")]
		public int id_investigador
		{
			get
			{
				return this._id_investigador;
			}
			set
			{
				if ((this._id_investigador != value))
				{
					this._id_investigador = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CentroTrabajo", DbType="VarChar(100)")]
		public string CentroTrabajo
		{
			get
			{
				return this._CentroTrabajo;
			}
			set
			{
				if ((this._CentroTrabajo != value))
				{
					this._CentroTrabajo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(100)")]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this._Correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Temas", DbType="VarChar(100)")]
		public string Temas
		{
			get
			{
				return this._Temas;
			}
			set
			{
				if ((this._Temas != value))
				{
					this._Temas = value;
				}
			}
		}
	}
	
	public partial class CP_listarRevistaCientificaFiltroResult
	{
		
		private int _id_revista;
		
		private string _Nombre;
		
		private string _Editor;
		
		private System.Nullable<System.DateTime> _AnioInicioPublicacion;
		
		private string _Frecuencia;
		
		private string _Temas;
		
		private System.Nullable<int> _Numero;
		
		private System.Nullable<System.DateTime> _AnioPublicacionActual;
		
		private System.Nullable<decimal> _Costo;
		
		public CP_listarRevistaCientificaFiltroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_revista", DbType="Int NOT NULL")]
		public int id_revista
		{
			get
			{
				return this._id_revista;
			}
			set
			{
				if ((this._id_revista != value))
				{
					this._id_revista = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Editor", DbType="VarChar(50)")]
		public string Editor
		{
			get
			{
				return this._Editor;
			}
			set
			{
				if ((this._Editor != value))
				{
					this._Editor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnioInicioPublicacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> AnioInicioPublicacion
		{
			get
			{
				return this._AnioInicioPublicacion;
			}
			set
			{
				if ((this._AnioInicioPublicacion != value))
				{
					this._AnioInicioPublicacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Frecuencia", DbType="VarChar(50)")]
		public string Frecuencia
		{
			get
			{
				return this._Frecuencia;
			}
			set
			{
				if ((this._Frecuencia != value))
				{
					this._Frecuencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Temas", DbType="VarChar(50)")]
		public string Temas
		{
			get
			{
				return this._Temas;
			}
			set
			{
				if ((this._Temas != value))
				{
					this._Temas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numero", DbType="Int")]
		public System.Nullable<int> Numero
		{
			get
			{
				return this._Numero;
			}
			set
			{
				if ((this._Numero != value))
				{
					this._Numero = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnioPublicacionActual", DbType="DateTime")]
		public System.Nullable<System.DateTime> AnioPublicacionActual
		{
			get
			{
				return this._AnioPublicacionActual;
			}
			set
			{
				if ((this._AnioPublicacionActual != value))
				{
					this._AnioPublicacionActual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Costo", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Costo
		{
			get
			{
				return this._Costo;
			}
			set
			{
				if ((this._Costo != value))
				{
					this._Costo = value;
				}
			}
		}
	}
	
	public partial class CP_ListarInformeTecnicoResult
	{
		
		private int _id_informe;
		
		private string _Numero;
		
		private string _CentroPublicacion;
		
		private string _MesPublicacion;
		
		private string _AñoPublicacion;
		
		public CP_ListarInformeTecnicoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_informe", DbType="Int NOT NULL")]
		public int id_informe
		{
			get
			{
				return this._id_informe;
			}
			set
			{
				if ((this._id_informe != value))
				{
					this._id_informe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numero", DbType="VarChar(100)")]
		public string Numero
		{
			get
			{
				return this._Numero;
			}
			set
			{
				if ((this._Numero != value))
				{
					this._Numero = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CentroPublicacion", DbType="VarChar(100)")]
		public string CentroPublicacion
		{
			get
			{
				return this._CentroPublicacion;
			}
			set
			{
				if ((this._CentroPublicacion != value))
				{
					this._CentroPublicacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MesPublicacion", DbType="VarChar(60)")]
		public string MesPublicacion
		{
			get
			{
				return this._MesPublicacion;
			}
			set
			{
				if ((this._MesPublicacion != value))
				{
					this._MesPublicacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AñoPublicacion", DbType="VarChar(100)")]
		public string AñoPublicacion
		{
			get
			{
				return this._AñoPublicacion;
			}
			set
			{
				if ((this._AñoPublicacion != value))
				{
					this._AñoPublicacion = value;
				}
			}
		}
	}
	
	public partial class CP_ListarRevistaCientificaResult
	{
		
		private int _id_revista;
		
		private string _Nombre;
		
		private string _Editor;
		
		private System.Nullable<System.DateTime> _AnioInicioPublicacion;
		
		private string _Frecuencia;
		
		private string _Temas;
		
		private System.Nullable<int> _Numero;
		
		private System.Nullable<System.DateTime> _AnioPublicacionActual;
		
		private System.Nullable<decimal> _Costo;
		
		public CP_ListarRevistaCientificaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_revista", DbType="Int NOT NULL")]
		public int id_revista
		{
			get
			{
				return this._id_revista;
			}
			set
			{
				if ((this._id_revista != value))
				{
					this._id_revista = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Editor", DbType="VarChar(50)")]
		public string Editor
		{
			get
			{
				return this._Editor;
			}
			set
			{
				if ((this._Editor != value))
				{
					this._Editor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnioInicioPublicacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> AnioInicioPublicacion
		{
			get
			{
				return this._AnioInicioPublicacion;
			}
			set
			{
				if ((this._AnioInicioPublicacion != value))
				{
					this._AnioInicioPublicacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Frecuencia", DbType="VarChar(50)")]
		public string Frecuencia
		{
			get
			{
				return this._Frecuencia;
			}
			set
			{
				if ((this._Frecuencia != value))
				{
					this._Frecuencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Temas", DbType="VarChar(50)")]
		public string Temas
		{
			get
			{
				return this._Temas;
			}
			set
			{
				if ((this._Temas != value))
				{
					this._Temas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numero", DbType="Int")]
		public System.Nullable<int> Numero
		{
			get
			{
				return this._Numero;
			}
			set
			{
				if ((this._Numero != value))
				{
					this._Numero = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnioPublicacionActual", DbType="DateTime")]
		public System.Nullable<System.DateTime> AnioPublicacionActual
		{
			get
			{
				return this._AnioPublicacionActual;
			}
			set
			{
				if ((this._AnioPublicacionActual != value))
				{
					this._AnioPublicacionActual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Costo", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Costo
		{
			get
			{
				return this._Costo;
			}
			set
			{
				if ((this._Costo != value))
				{
					this._Costo = value;
				}
			}
		}
	}
	
	public partial class CP_ListarActaCongresoResult
	{
		
		private int _id_actacongreso;
		
		private string _NombreCongreso;
		
		private string _Edicion;
		
		private string _CiudadCelebracion;
		
		private System.Nullable<System.DateTime> _FechaInicio;
		
		private System.Nullable<System.DateTime> _FechaFinalizacion;
		
		private string _TipoCongreso;
		
		private string _Pais;
		
		private string _AñoPrimeraCelebracion;
		
		private string _Frecuencia;
		
		public CP_ListarActaCongresoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_actacongreso", DbType="Int NOT NULL")]
		public int id_actacongreso
		{
			get
			{
				return this._id_actacongreso;
			}
			set
			{
				if ((this._id_actacongreso != value))
				{
					this._id_actacongreso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCongreso", DbType="VarChar(200)")]
		public string NombreCongreso
		{
			get
			{
				return this._NombreCongreso;
			}
			set
			{
				if ((this._NombreCongreso != value))
				{
					this._NombreCongreso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Edicion", DbType="VarChar(50)")]
		public string Edicion
		{
			get
			{
				return this._Edicion;
			}
			set
			{
				if ((this._Edicion != value))
				{
					this._Edicion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CiudadCelebracion", DbType="VarChar(150)")]
		public string CiudadCelebracion
		{
			get
			{
				return this._CiudadCelebracion;
			}
			set
			{
				if ((this._CiudadCelebracion != value))
				{
					this._CiudadCelebracion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaInicio", DbType="Date")]
		public System.Nullable<System.DateTime> FechaInicio
		{
			get
			{
				return this._FechaInicio;
			}
			set
			{
				if ((this._FechaInicio != value))
				{
					this._FechaInicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaFinalizacion", DbType="Date")]
		public System.Nullable<System.DateTime> FechaFinalizacion
		{
			get
			{
				return this._FechaFinalizacion;
			}
			set
			{
				if ((this._FechaFinalizacion != value))
				{
					this._FechaFinalizacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoCongreso", DbType="VarChar(40)")]
		public string TipoCongreso
		{
			get
			{
				return this._TipoCongreso;
			}
			set
			{
				if ((this._TipoCongreso != value))
				{
					this._TipoCongreso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pais", DbType="VarChar(150)")]
		public string Pais
		{
			get
			{
				return this._Pais;
			}
			set
			{
				if ((this._Pais != value))
				{
					this._Pais = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AñoPrimeraCelebracion", DbType="VarChar(100)")]
		public string AñoPrimeraCelebracion
		{
			get
			{
				return this._AñoPrimeraCelebracion;
			}
			set
			{
				if ((this._AñoPrimeraCelebracion != value))
				{
					this._AñoPrimeraCelebracion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Frecuencia", DbType="VarChar(50)")]
		public string Frecuencia
		{
			get
			{
				return this._Frecuencia;
			}
			set
			{
				if ((this._Frecuencia != value))
				{
					this._Frecuencia = value;
				}
			}
		}
	}
	
	public partial class CP_ListarInvestigador_ArticuloResult
	{
		
		private int _id_investigador;
		
		private int _id_articulo;
		
		public CP_ListarInvestigador_ArticuloResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_investigador", DbType="Int NOT NULL")]
		public int id_investigador
		{
			get
			{
				return this._id_investigador;
			}
			set
			{
				if ((this._id_investigador != value))
				{
					this._id_investigador = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_articulo", DbType="Int NOT NULL")]
		public int id_articulo
		{
			get
			{
				return this._id_articulo;
			}
			set
			{
				if ((this._id_articulo != value))
				{
					this._id_articulo = value;
				}
			}
		}
	}
	
	public partial class CP_ListarInvestigador_ArticuloFiltroResult
	{
		
		private int _id_investigador;
		
		private int _id_articulo;
		
		public CP_ListarInvestigador_ArticuloFiltroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_investigador", DbType="Int NOT NULL")]
		public int id_investigador
		{
			get
			{
				return this._id_investigador;
			}
			set
			{
				if ((this._id_investigador != value))
				{
					this._id_investigador = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_articulo", DbType="Int NOT NULL")]
		public int id_articulo
		{
			get
			{
				return this._id_articulo;
			}
			set
			{
				if ((this._id_articulo != value))
				{
					this._id_articulo = value;
				}
			}
		}
	}
	
	public partial class CP_ListarInvestigadores_ArticulosResult
	{
		
		private int _id_articulo;
		
		private string _Titulo;
		
		private int _id_investigador;
		
		private string _Nombre;
		
		public CP_ListarInvestigadores_ArticulosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_articulo", DbType="Int NOT NULL")]
		public int id_articulo
		{
			get
			{
				return this._id_articulo;
			}
			set
			{
				if ((this._id_articulo != value))
				{
					this._id_articulo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulo", DbType="VarChar(150)")]
		public string Titulo
		{
			get
			{
				return this._Titulo;
			}
			set
			{
				if ((this._Titulo != value))
				{
					this._Titulo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_investigador", DbType="Int NOT NULL")]
		public int id_investigador
		{
			get
			{
				return this._id_investigador;
			}
			set
			{
				if ((this._id_investigador != value))
				{
					this._id_investigador = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
	}
	
	public partial class CP_ListarActaArticuloResult
	{
		
		private int _id_actacongreso;
		
		private int _id_articulo;
		
		public CP_ListarActaArticuloResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_actacongreso", DbType="Int NOT NULL")]
		public int id_actacongreso
		{
			get
			{
				return this._id_actacongreso;
			}
			set
			{
				if ((this._id_actacongreso != value))
				{
					this._id_actacongreso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_articulo", DbType="Int NOT NULL")]
		public int id_articulo
		{
			get
			{
				return this._id_articulo;
			}
			set
			{
				if ((this._id_articulo != value))
				{
					this._id_articulo = value;
				}
			}
		}
	}
	
	public partial class CP_ListarActaArticuloFiltroResult
	{
		
		private int _id_actacongreso;
		
		private int _id_articulo;
		
		public CP_ListarActaArticuloFiltroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_actacongreso", DbType="Int NOT NULL")]
		public int id_actacongreso
		{
			get
			{
				return this._id_actacongreso;
			}
			set
			{
				if ((this._id_actacongreso != value))
				{
					this._id_actacongreso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_articulo", DbType="Int NOT NULL")]
		public int id_articulo
		{
			get
			{
				return this._id_articulo;
			}
			set
			{
				if ((this._id_articulo != value))
				{
					this._id_articulo = value;
				}
			}
		}
	}
	
	public partial class CP_ListarInformeArticuloResult
	{
		
		private int _id_informe;
		
		private int _id_articulo;
		
		public CP_ListarInformeArticuloResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_informe", DbType="Int NOT NULL")]
		public int id_informe
		{
			get
			{
				return this._id_informe;
			}
			set
			{
				if ((this._id_informe != value))
				{
					this._id_informe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_articulo", DbType="Int NOT NULL")]
		public int id_articulo
		{
			get
			{
				return this._id_articulo;
			}
			set
			{
				if ((this._id_articulo != value))
				{
					this._id_articulo = value;
				}
			}
		}
	}
	
	public partial class CP_ListarInformeArticuloFiltroResult
	{
		
		private int _id_informe;
		
		private int _id_articulo;
		
		public CP_ListarInformeArticuloFiltroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_informe", DbType="Int NOT NULL")]
		public int id_informe
		{
			get
			{
				return this._id_informe;
			}
			set
			{
				if ((this._id_informe != value))
				{
					this._id_informe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_articulo", DbType="Int NOT NULL")]
		public int id_articulo
		{
			get
			{
				return this._id_articulo;
			}
			set
			{
				if ((this._id_articulo != value))
				{
					this._id_articulo = value;
				}
			}
		}
	}
	
	public partial class CP_ListarV2RevistaArticuloResult
	{
		
		private int _id_articulo;
		
		private string _Titulo;
		
		private int _id_revista;
		
		private string _Nombre;
		
		private string _Editor;
		
		private System.Nullable<decimal> _Costo;
		
		public CP_ListarV2RevistaArticuloResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_articulo", DbType="Int NOT NULL")]
		public int id_articulo
		{
			get
			{
				return this._id_articulo;
			}
			set
			{
				if ((this._id_articulo != value))
				{
					this._id_articulo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulo", DbType="VarChar(150)")]
		public string Titulo
		{
			get
			{
				return this._Titulo;
			}
			set
			{
				if ((this._Titulo != value))
				{
					this._Titulo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_revista", DbType="Int NOT NULL")]
		public int id_revista
		{
			get
			{
				return this._id_revista;
			}
			set
			{
				if ((this._id_revista != value))
				{
					this._id_revista = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Editor", DbType="VarChar(50)")]
		public string Editor
		{
			get
			{
				return this._Editor;
			}
			set
			{
				if ((this._Editor != value))
				{
					this._Editor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Costo", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Costo
		{
			get
			{
				return this._Costo;
			}
			set
			{
				if ((this._Costo != value))
				{
					this._Costo = value;
				}
			}
		}
	}
	
	public partial class CP_ListarV2InformeArticuloResult
	{
		
		private int _id_informe;
		
		private string _Numero;
		
		private int _id_articulo;
		
		private string _Titulo;
		
		private string _CentroPublicacion;
		
		public CP_ListarV2InformeArticuloResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_informe", DbType="Int NOT NULL")]
		public int id_informe
		{
			get
			{
				return this._id_informe;
			}
			set
			{
				if ((this._id_informe != value))
				{
					this._id_informe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numero", DbType="VarChar(100)")]
		public string Numero
		{
			get
			{
				return this._Numero;
			}
			set
			{
				if ((this._Numero != value))
				{
					this._Numero = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_articulo", DbType="Int NOT NULL")]
		public int id_articulo
		{
			get
			{
				return this._id_articulo;
			}
			set
			{
				if ((this._id_articulo != value))
				{
					this._id_articulo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulo", DbType="VarChar(150)")]
		public string Titulo
		{
			get
			{
				return this._Titulo;
			}
			set
			{
				if ((this._Titulo != value))
				{
					this._Titulo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CentroPublicacion", DbType="VarChar(100)")]
		public string CentroPublicacion
		{
			get
			{
				return this._CentroPublicacion;
			}
			set
			{
				if ((this._CentroPublicacion != value))
				{
					this._CentroPublicacion = value;
				}
			}
		}
	}
	
	public partial class CP_ListarV2ActaArticuloResult
	{
		
		private int _id_articulo;
		
		private string _Titulo;
		
		private int _id_actacongreso;
		
		private string _NombreCongreso;
		
		private string _Edicion;
		
		private string _Frecuencia;
		
		public CP_ListarV2ActaArticuloResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_articulo", DbType="Int NOT NULL")]
		public int id_articulo
		{
			get
			{
				return this._id_articulo;
			}
			set
			{
				if ((this._id_articulo != value))
				{
					this._id_articulo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulo", DbType="VarChar(150)")]
		public string Titulo
		{
			get
			{
				return this._Titulo;
			}
			set
			{
				if ((this._Titulo != value))
				{
					this._Titulo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_actacongreso", DbType="Int NOT NULL")]
		public int id_actacongreso
		{
			get
			{
				return this._id_actacongreso;
			}
			set
			{
				if ((this._id_actacongreso != value))
				{
					this._id_actacongreso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCongreso", DbType="VarChar(200)")]
		public string NombreCongreso
		{
			get
			{
				return this._NombreCongreso;
			}
			set
			{
				if ((this._NombreCongreso != value))
				{
					this._NombreCongreso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Edicion", DbType="VarChar(50)")]
		public string Edicion
		{
			get
			{
				return this._Edicion;
			}
			set
			{
				if ((this._Edicion != value))
				{
					this._Edicion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Frecuencia", DbType="VarChar(50)")]
		public string Frecuencia
		{
			get
			{
				return this._Frecuencia;
			}
			set
			{
				if ((this._Frecuencia != value))
				{
					this._Frecuencia = value;
				}
			}
		}
	}
	
	public partial class CP_ListarRevistaArticuloResult
	{
		
		private System.Nullable<int> _IdRevista;
		
		private System.Nullable<int> _IdArticulo;
		
		public CP_ListarRevistaArticuloResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRevista", DbType="Int")]
		public System.Nullable<int> IdRevista
		{
			get
			{
				return this._IdRevista;
			}
			set
			{
				if ((this._IdRevista != value))
				{
					this._IdRevista = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdArticulo", DbType="Int")]
		public System.Nullable<int> IdArticulo
		{
			get
			{
				return this._IdArticulo;
			}
			set
			{
				if ((this._IdArticulo != value))
				{
					this._IdArticulo = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
